### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by htiz**
Add Exif

### CODE REVIEW

**Comment by tianon** [comment]
Before you open more of these, can you please explain a bit more the rationale, and why you're making so many PRs for it? :smile:

**Comment by tianon** [comment]
(To update a PR, you just need to force push to the same branch the PR's created from and it'll automatically update here.)

**Comment by tianon** [comment]
Why not roll all the updates into #53?

**Comment by htiz** [comment]
Oups sorry ! I suppose I made the mistake of creating a PR for each file I
modified.
Do you want me to redo it?

Thanks !

2016-03-10 16:37 GMT+01:00 Tianon Gravi notifications@github.com:

**Pull request closed without merging**
