### PR TITLE
Htiz branch1

### PR DESCRIPTION
**Pull request by htiz**
Propose to add EXIF module to automatically rotate pictures in Owncloud preview and Gallery

### CODE REVIEW

**Comment by pierreozoux** [comment]
I also noticed the bug!
+1 for exif :)

Could you update your PR for 7, 8.0, 8.1, 8.2 also please?

Thanks!

**Comment by tianon** [comment]
I'm not sure what the glitch was to create so many other PRs, but please just force push to this same branch and update this PR.  I'm +1 on the fix. :+1:

**Comment by htiz** [comment]
OK - put all changes in existing PR !

**Comment by pierreozoux** [comment]
LGTM, let's merge @tianon ?

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
