### PR TITLE
Install APCu version 4 explicitly now that 5 is also "stable" and only supports PHP 7+

### PR DESCRIPTION
**Pull request by tianon**
This fixes build failures thanks to APCu's dep change.

### CODE REVIEW

**Comment by tianon** [comment]
See https://travis-ci.org/docker-library/owncloud/jobs/97259123#L2565 for an example failure.

**Comment by tianon** [comment]
https://pecl.php.net/package/APCu has the proof that 5.1.2 and 4.0.10 were released to "stable" on the same day (2015-12-07), so this is supposedly the "correct" fix in upstream's eyes too :+1:

**Comment by lazyfrosch** [comment]
lgtm :+1: 

Since there is no better way to set version...

**Comment by tianon** [comment]
Yeah :cry:

Thanks for taking a look!

**Pull request merged**
