### PR TITLE
WIP: Apache Mod Gzip Bug Results in Terrible Cache Performance

### PR DESCRIPTION
**Pull request by lazyfrosch**
This is only to discuss #45

### CODE REVIEW

**Comment by lazyfrosch** [comment]
In my environment, I can't see any difference in load time.

I have a frontend Apache web server, that does SSL and public appearance, though I added the lines in my VHost there aswell.

I notice no difference in load time, it is ~ 4.6 sec for both versions.

**Comment by countable** [comment]
Ah, sorry, you may need to run

```
a2enmod headers
```

in the container, since the workaround depends on the apache2 headers module. You can tell if it's working by opening chrome devtools and seeing lots of 304 when refreshing repeated, instead of 200. It should be mostly 304 responses in the network tab of devtools, when resources are cached correctly, and should load on the order of 3 times faster overall with the 2 config lines I sent.

**Comment by lazyfrosch** [comment]
Okay, you are right, this seems to work.

Down to 1.3 - 1.47s

**Comment by lazyfrosch** [comment]
@tianon should we merge this in? I'd enable it for all the Apache's

**Comment by tianon** [comment]
This sounds generally sane, but I'd feel a lot better about it if we had an explicit recommendation from upstream to use this configuration (which we could then point to in a comment here as rationale) -- do their docs mention anything about this anywhere (maybe some kind of "tuning" section)?

**Comment by lazyfrosch** [comment]
Closing this, I'm having no problems with it...

**Pull request closed without merging**
